spring:
  application:
    name: rail
  datasource:
    url: jdbc:h2:mem:mydb
    password: ${PWD}
    username: sa
  jpa:
    hibernate.ddl-auto: validate
  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.yaml