spring:
  application:
    name: rail
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: ${PWD}
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.yaml