spring:
  application:
    name: rail
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: ${PWD}
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.xml

app:
  scheduling:
    enabled: false
    optimization: true
    fixedDelay: 10000 #ms
    priceIncreasePercentage: 10.1
    optimize:
      exclusive-lock: true
rest:
  currency-service:
    host: http://localhost:8081
    methods:
      get-currency: /api/v1/currencies
    mock:
      enabled: false
